### PR TITLE
Hi!!!

### PR DESCRIPTION
**Pull request by edvardoss**
Included some redaction about urca package

### CODE REVIEW

**Comment by IyarLin** [comment]
@edvardoss Could you please add the Rmd?

**Comment by edvardoss** [comment]
> @edvardoss Could you please add the Rmd?

Hi!
[forecast_git.zip](https://github.com/IyarLin/R-advantages-over-python/files/6782108/forecast_git.zip)

**Comment by edvardoss** [comment]
> @edvardoss Could you please add the Rmd?

Hi!
Rmd included

**Comment by IyarLin** [comment]
Merged via own commit. Thanks!

**Pull request closed without merging**
